name: Leep Staging CI/CD RN Android 
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  APP_CENTER_TOKEN: ${{ secrets.AC_TOKEN_PRN_ANDROID_STAGING  }}  
  APP_NAME: ${{ 'pipelinern/ENV_STAGING'  }}  
  TESTING_GROUP: ${{  'DEVOPS_STAGING'  }} 
  UPLOAD_FILE: ${{ 'android/app/build/outputs/apk/release/app-release.apk'  }}  
  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install dependencies
        run: npm install

      - name: Build android
        run: npm run &&  cd android && ./gradlew clean && ./gradlew assembleRelease

      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${{ env.APP_NAME }}
          token: ${{ env.APP_CENTER_TOKEN }}
          group: ${{ env.TESTING_GROUP }}
          file: ${{ env.UPLOAD_FILE }}
          notifyTesters: true
          debug: false
