name: Leep Staging CI/CD RN Android 
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install dependencies
        run: npm install

      - name: Build android
        run: npm run &&  cd android && ./gradlew clean && ./gradlew assembleRelease

      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: pipelinern/envstaging  
          token: e8c00fb1d26ee50b8be95c640b12cfa004203eae
          group: testers 
          file: app/build/outputs/apk/release/app-release.apk  
          notifyTesters: true
          debug: false
